/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicLayout: typeof import('./src/components/basic/basicLayout/index.vue')['default']
    BasicModel: typeof import('./src/components/basic/basicModel.vue')['default']
    ColumSetting: typeof import('./src/components/basic/basicLayout/components/columSetting.vue')['default']
    Icon: typeof import('./src/components/icon/index.vue')['default']
    Markdown: typeof import('./src/components/markdown/index.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    QueryItem: typeof import('./src/components/basic/queryItem.vue')['default']
    RichText: typeof import('./src/components/richText/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/icon/svgIcon.vue')['default']
    TableAction: typeof import('./src/components/basic/tableAction.vue')['default']
  }
}
