name: GithubDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      #下载代码仓库
      - uses: actions/checkout@v1

      # 使用action库，安装node
      - name: use Node.js # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 18.17.0 # 指定node版本
      # 安装依赖
      - name: Install and Build
        run: |
          npm install pnpm -g && \
          pnpm install --no-frozen-lockfile && \
          pnpm build:github

      # 部署到github pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: dist
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}