name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      #下载代码仓库
      - uses: actions/checkout@v1

      # 使用action库，安装node
      - name: use Node.js # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 18.17.0 # 指定node版本
      # 安装依赖
      - name: Install and Build
        run: |
          npm install pnpm -g && \
          pnpm install --no-frozen-lockfile && \
          pnpm build

      #部署到服务器
      - name: Deploy to Staging My server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          #私钥
          SSH_PRIVATE_KEY: ${{ secrets.SSHPWD }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist"
          REMOTE_HOST: ${{ secrets.HOST }} #服务器ip
          REMOTE_USER: "root"
          TARGET: "/home/Unusual-Admin/"
          EXCLUDE: "/node_modules/"