name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 下载代码仓库
      - uses: actions/checkout@v2

      # 使用 action 库，安装 Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      # 安装依赖并构建
      - name: Install and Build
        run: |
          npm install -g pnpm && \
          pnpm install --no-frozen-lockfile && \
          pnpm build

      # 设置 SSH 主机密钥
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSHPWD }}

      # 设置 known_hosts
      - name: Set up known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # 使用 rsync 同步文件到服务器
      - name: Sync files to server
        run: |
          rsync -avz --delete ./dist ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/Unusual-Admin/dist
          rsync -avz --delete ./Dockerfile ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/Unusual-Admin/Dockerfile
          rsync -avz --delete ./nginx.config ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/Unusual-Admin/nginx.config

      # 设置脚本权限
      - name: Set script permissions
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'chmod +x /home/Unusual-Admin/web-setup.sh'

      # 执行脚本
      - name: Execute script on server
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'bash /home/Unusual-Admin/web-setup.sh'
