name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSHPWD }}
      REMOTE_HOST: ${{ secrets.HOST }}
      REMOTE_USER: ${{ secrets.USERNAME }}

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: 安装和构建
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm build

      - name: 部署到服务器
        uses: easingthemes/ssh-deploy@v2.1.6
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSHPWD }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist DockerFile nginx.conf"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/home/Unusual-Admin/"
          EXCLUDE: "/node_modules/"

      - name: 构建 Docker 镜像
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'docker build -t myapp:latest /home/Unusual-Admin/' || exit 1

      - name: 部署 Docker 容器
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 80:80 myapp:latest
          EOF
